name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install

    - name: Copy files to EC2 via rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync  # Ensure rsync is installed
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY }}" ./ ubuntu@13.232.27.148:/var/www/my-app/backend/micro-services-backend

    - name: SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY }} ubuntu@13.232.27.148 << 'EOF'
          cd /var/www/my-app/backend/micro-services-backend
          npm install    # Install dependencies on the server
          sudo systemctl restart nginx   # Restart Nginx service
          pm2 restart all  # Restart all PM2 processes
        EOF
